version: "3.9"
services:
    backend:
        image: backend
        build:
            context: ./backend
        ports:
            - "8080:8080"
        container_name: backend
        depends_on:
          - db
        environment:
          - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/taskdb
          - SPRING_DATASOURCE_USERNAME=postgresadminexample
          - SPRING_DATASOURCE_PASSWORD=myhiddenpostgrespw
          - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    frontend:
        image: frontend
        container_name: frontend
        build:
            context: ./frontend
        ports:
            - "4200:80"
        depends_on:
            - backend
    
    db:
        image: 'postgres:13.1-alpine'
        container_name: db
        environment:
          POSTGRES_DB: taskdb
          POSTGRES_USER: postgresadminexample
          POSTGRES_PASSWORD: myhiddenpostgrespw